services:
  bucstop:
    build:
      context: ./Bucstop_WebApp/BucStop
      dockerfile: Dockerfile
    container_name: bucstop
    ports:
      - "8080:8000"  # Changed from 80 -> 8000
    networks:
      - bucstop-network
    environment:
      - ASPNETCORE_URLS=http://+:8000  # Changed from 80 -> 8000
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_HTTPS_PORT=
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./BucStop_APIGateway/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:5000"  # Changed from 80 -> 5000
    networks:
      - bucstop-network
    depends_on:
      - snake
      - pong
      - tetris

  snake:
    build:
      context: ./BucStop_Snake/Snake
      dockerfile: Dockerfile
    container_name: game-snake
    ports:
      - "8082:5001"  # Changed from 80 -> 5001
    networks:
      - bucstop-network

  pong:
    build:
      context: ./BucStop_Pong/Pong
      dockerfile: Dockerfile
    container_name: game-pong
    ports:
      - "8083:5003"  # Changed from 80 -> 5003
    networks:
      - bucstop-network

  tetris:
    build:
      context: ./BucStop_Tetris/Tetris
      dockerfile: Dockerfile
    container_name: game-tetris
    ports:
      - "8084:5002"  # Changed from 80 -> 5002
    networks:
      - bucstop-network

networks:
  bucstop-network:
    driver: bridge
